#!/bin/bash
#
# sesioonide maaramine
#
echo -n "Sisesta kuu number: "
read kuu
#
if [ $kuu -eq 1-o $kuu -eq 2 -o $kuu -eq 12 ]; then
	echo "Preagu on talv"
elif [ $kuu -eq 3 -o $kuu -eq 4 -o $kuu -eq 5 ]; then
	echo "Preagu on kevad"
fi

